server:
  servlet:
    context-path: /api-usuario
spring:
 application:
  name: usuario
 datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
    
 h2:
     console:
      enabled: true
      path: /h2-console
      
security:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}      