server:
 servlet:
  context-path: /usuario/api
 port: 8181    
logging:
 level:
  com.github.joanersoncosta.api: ${LOG_LEVEL:DEBUG}    
spring:
 application:
  name: msboleto
 datasource:
  url: jdbc:h2:mem:boleto
  driver-class-name: org.h2.Driver
  username: admin
  password: 1234
 h2:
  console:
   enabled: true
   path: /h2-console
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: false  
